name: frontend
description: Team meeting client
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  web_socket_channel: ^3.0.1
  flutter_dotenv: ^5.1.0
  dio: ^5.7.0
  shared_preferences: ^2.2.0
  go_router: ^14.2.7
  flutter_riverpod: ^2.5.1
  record: ^5.0.5

dependency_overrides:
  record_linux: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
